version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      versioning-strategy: increase-if-necessary
      open-pull-requests-limit: 10
      pull-request-branch-name:
          separator: '-'
      schedule:
          interval: 'monthly'
      labels:
          - 'npm'
          - 'dependencies'
      allow:
          - dependency-type: 'production'
      commit-message:
          prefix: 'npm prod'
          prefix-development: 'npm dev'
          include: 'scope'
