name: Deploy serverless app

on:
    push:
        branches:
            - main
            - dev

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: serverless deploy
              uses: serverless/github-action@v3.1
              with:
                  args: deploy -c ./serverless.yml
                  entrypoint: /bin/sh
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
                  SLS_DEBUG: 1
